window.Configuration = {}
window.Configuration.OAuthURL = 'https://project.oauth.eduworks.com/';
window.Configuration.OAuthToken = '86ujpjdo6nv82l';
window.Configuration.lrsUrl = 'https://lrs.peblproject.com/';
window.Configuration.lrsCredential = 'MTFkZWU2MDg1NTMyZGM4YzE4ZTQyMDFiMGY2YmE4NjE0NTBhMmI3NzoyMGFkNzM3NWE5YjcwYWY1OWJiYzM3ZWZhNjJlYTNlOGNlM2MyMGUw';
window.Configuration.useLinkedIn = false;
window.Configuration.favicon = 'images/PEBL-icon-16.ico';
window.Configuration.loginImage = 'images/PEBL-Logo-Color-small.png';
window.Configuration.userList = ['Learner', 'Learner1', 'Learner2', 'Learner3', 'Learner5', 'Learner7'];
